const NavBarList = [
    {
        name:'首页',
        path:'/'
    },
    {
        name:'商家管理',
        path:'/store',
        children:[
            {
                name:'登录日志',
                path:'/log'
            },
            {
                name:'商家设置',
                path:'/edit'
            },
            {
                name:'修改密码',
                path:'/resetPassword'
            },
            {
                name:'店铺链接',
                path:'/link'
            }
        ]
    },
    {
        name:'商品管理',
        path:'/goods',
        children:[
            {
                name:'商品分类',
                path:'/sort'
            },
            {
                name:'添加商品',
                path:'/add'
            },
            {
                name:'商品列表',
                path:'/list'
            },
            {
                name:'回收站',
                path:'/recycle'
            }
        ]
    },
    {
        name:'虚拟卡管理',
        path:'/card',
        children:[
            {
                name:'虚拟卡列表',
                path:'/list'
            },
            {
                name:'添加虚拟卡',
                path:'/add'
            },
            {
                name:'回收站',
                path:'/recycle'
            }
        ]
    },
    {
        name:'订单管理',
        path:'/order',
        children:[
            {
                name:'订单列表',
                path:'/list'
            },
            {
                name:'收益分析',
                path:'/analysis'
            }
        ]
    },
    {
        name:'提现管理',
        path:'/withdraw',
        children:[
            {
                name:'申请提现',
                path:'/apply'
            },
            {
                name:'提现列表',
                path:'/list'
            }
        ]
    }
]

export default NavBarList